---
title: "Problem Set 5"
author: "Anastasia Bernat"
output: html_document
---
# Problem Set 5 | 6 May 2020 - 13 May 2020 at 10 AM

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Answer the following conceptual questions.

(i) Other than its contents, what are the three properties of a vector?

(ii) List the four common types of atomic vectors. What are the two rare types?

(iii) Describe the difference between an if-if statement and an else if statement and code an example that highlights the diffence.

(iv) What are attributes? How do you get them and set them? Code an example.

(v) Describe all the possible differences between a list and an atomic vector and between a matrix and a dataframe.

(vi) Can you have a list that is a matrix? Can a data frame have a column that is a matrix?

(vii) Can you take the sum() of a list? Can you have a 2-D vector (aka. a vector of vectors)?

(viii) How many data structures does R language have? What's the difference between them?

(ix) Let's say you have some dataframe, d. What is d[1,]? What is dd[, 5].

(x) If you had a list of lists, ll, how would you get 1 element in the 4th column and 3rd row.
